name: catering_core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: null
  connectivity: null
  device_preview: ^1.1.0
  dio: null
  flare_flutter: null
  flutter_bloc: null
  icons_flutter: null
  flutter_keyboard_visibility: null
  flutter_spinkit: null
  get: null
  google_fonts: 
  grouped_list: null
  http: null
  intl: null
  image_picker: null
  json_table: null
  modal_bottom_sheet: null
  path_provider: null
  persistent_bottom_nav_bar:
  pull_to_refresh: null
  random_string: null
  share: null
  shared_preferences: null
  firebase_core: 
  firebase_messaging:
  flutter_local_notifications: ^15.1.0+1
  flutter_ringtone_player: null
  fl_chart:
  random_color:
  package_info:
  screenshot: ^2.1.0
  qr_flutter: null
  custom_clippers: null
  lottie: null
  flutter_otp_text_field: null
  flutter_launcher_icons: null
  url_launcher: null
  get_it: null
  dartz: null
  flutter_animate: null
  flutter_speed_dial: null
  rive: null
  # bluetooth_print: null
  blue_thermal_printer: ^1.2.3
  paginated_listview_builder: ^1.0.3
  firebase_remote_config: ^4.2.3
  month_picker_dialog: ^2.0.2
  webview_flutter: ^4.2.2
  flutter_slidable: ^3.0.0
  flutter_custom_clippers: ^2.1.0
  file_picker: ^5.3.3
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/anim/
    - assets/json/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
